function [fxy_exact, gxy_exact,...
    uxy_exact,vxy_exact,...
    dxy_exact,...
    m,m1,m2,...
    n,n1,n2,...
    t_exact,t1_exact,t2_exact]  = Examples_GCD(ex_num)
% Examples_GCD(ex_num)
% Get the coefficient matrix of the polynomials f(x,y), g(x,y), the GCD
% d(x,y), and cofactors u(x,y) and v(x,y) as well as their corresponding
% degrees.
%
% This file either produces an example from coefficient matrices or 
% 'from roots' where the coefficient matrices are generated.

EXAMPLE_TYPE = 'From Coefficients';

switch EXAMPLE_TYPE
    case 'From Roots'
        
        % Get example polynomials
        [fxy_exact, gxy_exact,...
            uxy_exact,vxy_exact,...
            dxy_exact,...
            m,m1,m2,...
            n,n1,n2,...
            t_exact,t1_exact,t2_exact] = Examples_GCD_FromRoots(ex_num);
        
    case 'From Coefficients'
        [fxy_exact, gxy_exact,...
            uxy_exact,vxy_exact,...
            dxy_exact,...
            m,m1,m2,...
            n,n1,n2,...
            t_exact,t1_exact,t2_exact] = Examples_GCD_FromCoefficients(ex_num);
        
end
end


